### ISSUE TITLE
[Пожелание] Добавить отправку расписания ВКонтакте и Telegram

### ISSUE THREAD

**Issue by ZemlyakovDmitry** [Ulbandus/e-school#1]
Привет! Очень круто, что есть такой клиент. А как на счёт сделать чат-бота для Телеги и ВК? 
Т.е. запустил у себя на VPS/VDS/Дедике бота (указав в конфиге все токены и данные, конечно), написал в беседу с группой "@bot_name_eschool Расписание на завтра", а бот отправит расписание. 

Спасибо.

**Comment by Ulbandus** [comment]
Отличная идея! Можно будет сделать после того, как доведу до ума этот проект.

**Comment by homus32** [comment]
Сейчас я делаю бота для вк.

Вот адрес
https://vk.com/netschool_bot
